#! /bin/bash

# Grab full name of mysql container
DB_CONTAINER=$(docker-compose ps | grep mysql | cut -d" " -f 1)

docker exec -i $DB_CONTAINER mysql -uroot -proot < mysql/sites/cpo/schema.sql
docker exec -i $DB_CONTAINER mysql -uroot -proot < mysql/sites/cpo/test_schema.sql
docker exec -i $DB_CONTAINER mysql -uroot -proot -e"show databases"
